<!DOCTYPE html/>
<html> lang ="pt-br">
    <head>
        <meta charset="utf-8">
        <title>"Minha página"</title>
    <body>
        <nav> 
            <p>Minha página</p>
            <ul>
                <li>
                    <a href="servicos">SERVICOS</a>
                </li>
                <li>
                    <a href="alunos">ALUNOS</a>
                </li>
                <li>
                    <a href="professores">PROFESSORES</a>
                </li>                  
                <li>
                    <a href="# time">TIME</a>
                </li>
                <li>
                    <a href="# contato">CONTATO</a>
                </li>
            </ul>
        </nav>    
        <header>
            <h1>Minha página</h1>
            <p>Oferecemos os melhores serviços e educação de qualidade.</p>
        </header>
                
        <section id="serviços">
            <h2>SERVIÇOS</h2>
            <P>Oferecemos os melhores serviços e educação de qualidade.</p>
            <div> 
                <img src="img/site.jpg" width="300px">
                <img src="img/app.jpg" width="300px">                               
            
        <section id="CLIENTE">
            <h2>Clientes</h2>
            <p>Nossos Alunos ficararão muito satisfeitos.</p>
            <div>
                <img src="img/Cliente1.jpg" width="300px"> 
          
        <section> id="Parceiros">
            <h2><PARCEIROS"></h2>
            <p>Os nossos parceiros (Professores e contribuintes) nos ajudam a ter um serviço de qualidade e excelência!</p>
            <div>
                <a href="https://digitalinnovation.one" target="blank">
                <img src="img/digital_innovation_one.png" width="130px"></a>                
        
    <footer>
            <p>Desenvolvido por BelisnalvaC</P>                
    </footer>
                
       

